global:
  slack_api_url_file: '/etc/alertmanager/slack-url.txt'
  resolve_timeout: 10s

route:
  receiver: 'slack-notifications'
  group_by: [alertname, datacenter, app]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 15s

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    text: 'https://internal.myorg.net/wiki/alerts/{{ .GroupLabels.app }}/{{ .GroupLabels.alertname }}'
