global:
  slack_api_url_file: '/etc/alertmanager/slack-url.txt'

route:
  receiver: 'slack-notifications'
  group_by: [alertname, datacenter, app]
  group_wait: 10s

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    text: 'https://internal.myorg.net/wiki/alerts/{{ .GroupLabels.app }}/{{ .GroupLabels.alertname }}'
