global:
  slack_api_url_file: '/etc/alertmanager/slack-url.txt'
  resolve_timeout: 10s

route:
  receiver: 'default-notifications'
  group_by: [alertname, datacenter, app]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 15s
  routes:
  - receiver: 'external-notifications'
    continue: true
  - receiver: 'default-notifications'
    continue: true

receivers:
- name: 'default-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    text: 'https://internal.myorg.net/wiki/alerts/{{ .GroupLabels.app }}/{{ .GroupLabels.alertname }} Description: {{ .CommonAnnotations.description }} Summary: {{ .CommonAnnotations.summary }}'
- name: 'external-notifications'
  webhook_configs:
  - url: 'http://custom-ticket:8081/data'
    send_resolved: true
