version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager:v0.25.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - "./alertmanager/slack-url.txt:/etc/alertmanager/slack-url.txt"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  node-app:
    image: andreformento/node-app
    build: ./node-app
    ports:
      - 8080:8080
    expose:
      - 8080

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
