groups:
- name: Instances
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: page
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
      summary: 'Instance {{ $labels.instance }} down'
- name: example
  rules:
  - alert: HighHttpRequestDuration
    expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
    for: 15s
    labels:
      severity: critical
    annotations:
      summary: "High HTTP request duration"
      description: "The average HTTP request duration is above 1 second over the last 5 minutes."
